### ISSUE TITLE
run.py throws unhandled exception while logging in

### ISSUE THREAD

**Issue by itsyigid** [hruzgar/ukey-downloader#2]
I double-checked my password and username, they are not wrong. 

Using
 - Version 98.0.4758.80 (Official Build, ungoogled-chromium) Arch Linux (64-bit)
 - ChromeDriver 98.0.4758.80

Exception message:
> Traceback (most recent call last):
>   File "/home/ferit/repos/ukey-downloader/run.py", line 226, in <module>
>     main()
>   File "/home/ferit/repos/ukey-downloader/run.py", line 189, in main
>     password_true = log_in(driver)
>   File "/home/ferit/repos/ukey-downloader/run.py", line 88, in log_in
>     pw.send_keys(passw)
>   File "/home/ferit/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 540, in send_keys
>     self._execute(Command.SEND_KEYS_TO_ELEMENT,
>   File "/home/ferit/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
>     return self._parent.execute(command, params)
>   File "/home/ferit/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
>     self.error_handler.check_response(response)
>   File "/home/ferit/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot construct KeyEvent from non-typeable key
>   (Session info: headless chrome=98.0.4758.80)
> Stacktrace:
> #0 0x555f1d977113 <unknown>
> .
> .
> #21 0x7fedfbdef259 <unknown>

**Comment by itsyigid** [comment]
After further debugging and research I have stumbled across this StackOverflow post: https://stackoverflow.com/questions/71112723/cannot-construct-keyevent-from-non-typeable-key-only-with-special-characters-us

My password contains special characters (which is a nice thing =P) that ChromeDriver v98 cannot handle very well. Accourding to the first post, this issue should resolve itself after a update to ChromeDriver v99, but if it doesn't resolve manual intervention and possible changes in script has to be made. In the next post, a possible fix for this issue is available:
https://stackoverflow.com/questions/70967207/selenium-chromedriver-cannot-construct-keyevent-from-non-typeable-key

**Comment by itsyigid** [comment]
After downgrading to ChromeDriver version 97, this issue has resolved. It seems that ChromeDriver v98 is faulty, therefore a warning should be included in README about it.

**Comment by hruzgar** [comment]
As you already figured out the issue is present with v98 of Chromedriver. Downgrading to v97 solved the problem!
