### ISSUE TITLE
Use "ukeydl" instead of "ukey-downloader" as program name

### ISSUE THREAD

**Issue by itsyigid** [hruzgar/ukey-downloader#5]
ukeydl is a better name because it follows the naming convention used in many FOSS scrapers and downloaders. ukey-downloader should stay as the project name that develops ukeydl

**Comment by itsyigid** [comment]
I will update relevant lines in the run.py to use "ukeydl" if @hruzgar agrees with me, and push a commit closing this issue

**Comment by hruzgar** [comment]
Yeah this naming would be much better! Thank you for your efforts
